# -*- coding: utf-8 -*-
"""Copy of dronedection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WuGpsP66UcfjsHPNlAKtGEt7tY1VuXuq
"""

from google.colab import drive
drive.mount('/content/drive')

# core libs
!pip install -U ultralytics kaggle roboflow opencv-python matplotlib tqdm

# if you plan to do fine-grained classification later:
!pip install timm torchvision

!mkdir -p /content/aod4
!unzip "/content/drive/MyDrive/archive .zip" -d /content/aod4
!ls -R /content/aod4 | head -40

data_yaml = """
path: /content/aod4
train: images/train
val: images/val
nc: 4
names: ['airplane','bird','drone','helicopter']
"""
with open("/content/aod4/data.yaml", "w") as f:
    f.write(data_yaml)

!ls -R /content/aod4 | head -40

data_yaml = """
path: /content/aod4
train: train/images
val: valid/images
nc: 4
names: ['airplane','bird','drone','helicopter']
"""
with open("/content/aod4/data.yaml", "w") as f:
    f.write(data_yaml)

!ls /content/aod4 -R

from ultralytics import YOLO

# Load the best model from the previous training run
model = YOLO('/content/drive/MyDrive/aod4_best.pt')  # Load your saved best weights

# Continue training for a total of 50 epochs
model.train(
    data='/content/aod4/data.yaml',
    epochs=40,  # Set the total number of epochs you want to reach
    imgsz=640,
    batch=16,
    name='aod4_yolov8n_continued' # Give a new name to the continued training run
)

from google.colab import drive
drive.mount('/content/drive')

# Copy best model to your Drive
# The model is saved in a directory named after your training run
!cp /content/runs/detect/aod4_yolov8n_continued/weights/best.pt /content/drive/MyDrive/aod4_best_continued.pt

from ultralytics import YOLO

# Load model from Google Drive
model = YOLO("/content/drive/MyDrive/aod4_best_continued.pt")

# Run prediction on an image
results = model.predict(source="/content/aod4/test/images/20190925_101846_1_1_000_jpg.rf.497f3eb572bec39e6856f75fc88b3d1b.jpg", save=True)

# Evaluate model performance on validation set
metrics = model.val()

# Run prediction on a sample image
results = model.predict(source='/content/aod4/test/images/20190925_101846_1_1_000_jpg.rf.497f3eb572bec39e6856f75fc88b3d1b.jpg', save=True, conf=0.25)

import os
from IPython.display import Image, display

# Replace with the actual filename of an image with bird detections from the test set
image_filename = "jasinthan-yoganathan-9exeLsj-cR8-unsplash_jpg.rf.376105bedef8000cd36d92fd1fa5916b.jpg"

# Find the latest prediction run directory
runs_dir = '/content/runs/detect/'
latest_run = sorted([d for d in os.listdir(runs_dir) if os.path.isdir(os.path.join(runs_dir, d))])[-1]
predicted_image_path = os.path.join(runs_dir, latest_run, image_filename)

# Display the image if it exists
if os.path.exists(predicted_image_path):
    display(Image(filename=predicted_image_path))
else:
    print(f"Predicted image not found at: {predicted_image_path}")

import os
from IPython.display import Image, display
from ultralytics import YOLO

# Load model from Google Drive
model = YOLO("/content/drive/MyDrive/aod4_best_continued.pt")

# Path to the test images directory
test_images_dir = '/content/aod4/test/images/'

# Get list of all image files in the test directory
image_files = [f for f in os.listdir(test_images_dir) if f.endswith(('.jpg', '.jpeg', '.png'))]

# Iterate through each image file
for image_file in image_files:
    image_path = os.path.join(test_images_dir, image_file)

    # Run prediction on the current image
    results = model.predict(source=image_path, save=True, conf=0.25)

    # Check if any detections are found and if the detected classes include 'airplane' or 'bird'
    if results and len(results[0].boxes) > 0:
        detected_classes = [model.names[int(box.cls)] for box in results[0].boxes]
        if 'airplane' in detected_classes or 'bird' in detected_classes:
            print(f"Detected airplane or bird in: {image_file}")
            # Display the image with predictions
            # The output directory changes based on the run, so we find the latest run directory
            runs_dir = '/content/runs/detect/'
            latest_run = sorted([d for d in os.listdir(runs_dir) if os.path.isdir(os.path.join(runs_dir, d))])[-1]
            # Construct the predicted image path based on the observed output structure
            predicted_image_path = os.path.join(runs_dir, latest_run, image_file)
            if os.path.exists(predicted_image_path):
                display(Image(filename=predicted_image_path))
            else:
                print(f"Predicted image not found at: {predicted_image_path}")

from ultralytics import YOLO
from IPython.display import Image, display
import os

# Load the best model
model = YOLO("/content/drive/MyDrive/aod4_best_continued.pt")

# Path to the image you want to predict on
image_to_predict = "/content/aod4/test/images/yt-0BFf4YWpzHM-0181_jpg.rf.2b0945721cc7d77fe8012ba02ab523d4.jpg" # Replace with your image path

# Run prediction
results = model.predict(source=image_to_predict, save=True, conf=0.25)

# Check if any detections are found and if the detected classes include 'airplane' or 'bird'
if results and len(results[0].boxes) > 0:
    detected_classes = [model.names[int(box.cls)] for box in results[0].boxes]
    if 'airplane' in detected_classes or 'bird' in detected_classes:
        print(f"Detected airplane or bird in: {image_to_predict}")
        # Display the image with predictions
        # The output directory changes based on the run, so we find the latest run directory
        runs_dir = '/content/runs/detect/'
        latest_run = sorted([d for d in os.listdir(runs_dir) if os.path.isdir(os.path.join(runs_dir, d))])[-1]
        # Extract just the filename from the image_to_predict path
        image_filename = os.path.basename(image_to_predict)
        predicted_image_path = os.path.join(runs_dir, latest_run, image_filename)
        if os.path.exists(predicted_image_path):
            display(Image(filename=predicted_image_path))
        else:
            print(f"Predicted image not found at: {predicted_image_path}")

import os
from IPython.display import Image, display

# Replace with the actual filename of an image with helicopter detections from the test set
image_filename = "V_HELICOPTER_051275_151_png_jpg.rf.0647c9d1cee197dced99c3cbde285ad7.jpg"

# Find the latest prediction run directory
runs_dir = '/content/runs/detect/'
# Get all entries in runs_dir that are directories
all_runs = [d for d in os.listdir(runs_dir) if os.path.isdir(os.path.join(runs_dir, d))]
# Filter out the 'val' directory if it's present
prediction_runs = [d for d in all_runs if not d.startswith('val')]
# Sort the prediction run directories and get the latest one
latest_run = sorted(prediction_runs)[-1] if prediction_runs else None

predicted_image_path = os.path.join(runs_dir, latest_run, image_filename)

# Display the image if it exists
if latest_run and os.path.exists(predicted_image_path):
    display(Image(filename=predicted_image_path))
else:
    print(f"Predicted image not found at: {predicted_image_path}")

from IPython.display import Image
Image(filename="/content/runs/detect/predict/20190925_101846_1_1_000_jpg.rf.497f3eb572bec39e6856f75fc88b3d1b.jpg")

import os
from IPython.display import Image, display
from ultralytics import YOLO

# Load the best model
model = YOLO("/content/drive/MyDrive/aod4_best.pt")

# Path to the image you want to predict on
image_to_predict = "/content/aod4/test/images/V_DRONE_047157_041_png_jpg.rf.e5965ebd4d8bd736c28328019350646e.jpg"

# Run prediction on the image and save the results
# save=True will save the predicted image with bounding boxes
results = model.predict(source=image_to_predict, save=True, conf=0.25)

# Find the latest prediction run directory
runs_dir = '/content/runs/detect/'
all_runs = [d for d in os.listdir(runs_dir) if os.path.isdir(os.path.join(runs_dir, d))]
prediction_runs = sorted([d for d in all_runs if d.startswith('predict')],
                         key=lambda x: int(x.replace('predict', '')) if x.replace('predict', '').isdigit() else 0)

# Corrected indexing to get the directory name from the tuple
latest_run = prediction_runs[-1] if prediction_runs else None
if latest_run and isinstance(latest_run, tuple): # Ensure it's a tuple before accessing the second element
    latest_run = latest_run[1]
elif latest_run and isinstance(latest_run, str):
    # If it's already a string (from a previous predict run not sorted numerically), use it directly
    pass


# Construct the expected path to the predicted image
predicted_image_filename = os.path.basename(image_to_predict)
predicted_image_path = os.path.join(runs_dir, latest_run, predicted_image_filename) if latest_run else None


print(f"--- Prediction Results ---")
if results and len(results[0].boxes) > 0:
    detected_classes = [model.names[int(box.cls)] for box in results[0].boxes]
    print(f"Detected classes: {detected_classes}")

    if 'drone' in detected_classes:
        print("A drone was detected in the image during this prediction run.")

        # Check if the predicted image file was saved
        if predicted_image_path and os.path.exists(predicted_image_path):
            print(f"Predicted image found at: {predicted_image_path}")
            print("\nDisplaying the predicted image:")
            display(Image(filename=predicted_image_path))
        elif predicted_image_path:
             print(f"Predicted image file not found at the expected path: {predicted_image_path}")
             print("Listing files in the latest prediction directory:")
             if latest_run and os.path.exists(os.path.join(runs_dir, latest_run)): # Added check for directory existence
                 print(os.listdir(os.path.join(runs_dir, latest_run)))
             else:
                 print("Could not determine or access the latest prediction directory.")
        else:
             print("Could not determine the expected path for the predicted image.")

    else:
        print("No drone was detected in the image during this prediction run.")
        if predicted_image_path and os.path.exists(predicted_image_path):
             print(f"Predicted image was still saved at: {predicted_image_path}")
             print("\nDisplaying the predicted image:")
             display(Image(filename=predicted_image_path))


elif results:
    print("No objects were detected in the image during this prediction run.")
    if predicted_image_path and os.path.exists(predicted_image_path):
        print(f"Predicted image was still saved at: {predicted_image_path}")
        print("\nDisplaying the predicted image:")
        display(Image(filename=predicted_image_path))

else:
    print("Prediction did not return any results.")

print(f"--- End of Prediction Results ---")

import os
from IPython.display import Image, display
from ultralytics import YOLO

# Load the best model
model = YOLO("/content/drive/MyDrive/aod4_best_continued.pt")

# Replace with the actual filename of an image with airplane or bird detections
# You can find the filenames in the output of the previous cell that iterated through the test set
image_to_predict_path = "/content/aod4/test/images/yt-0BFf4YWpzHM-0181_jpg.rf.2b0945721cc7d77fe8012ba02ab523d4.jpg"

# Run prediction on the image and save the results
# save=True will save the predicted image with bounding boxes
results = model.predict(source=image_to_predict_path, save=True, conf=0.25)

# Find the latest prediction run directory
runs_dir = '/content/runs/detect/'
print(f"Checking directory: {runs_dir}")
if not os.path.exists(runs_dir):
    print(f"Error: The directory {runs_dir} does not exist.")
else:
    all_runs = [d for d in os.listdir(runs_dir) if os.path.isdir(os.path.join(runs_dir, d))]
    print(f"All entries in {runs_dir}: {all_runs}")

    # Filter out directories that don't start with 'predict' and sort them numerically
    prediction_runs = []
    for d in all_runs:
        if d.startswith('predict'):
            try:
                run_number = int(d.replace('predict', ''))
                prediction_runs.append((run_number, d))
            except ValueError:
                # Ignore directories that don't have a valid number after 'predict'
                pass

    # Get the directory name of the latest prediction run
    latest_run_info = sorted(prediction_runs)[-1] if prediction_runs else None
    latest_run = latest_run_info[1] if latest_run_info else None

    print(f"Latest prediction run directory identified: {latest_run}")

    # Construct the predicted image path and display the image if it exists
    if latest_run:
        image_filename = os.path.basename(image_to_predict_path)
        predicted_image_path = os.path.join(runs_dir, latest_run, image_filename)
        print(f"Attempting to find predicted image at: {predicted_image_path}")

        if os.path.exists(predicted_image_path):
            print(f"Predicted image found.")
            display(Image(filename=predicted_image_path))
        else:
            print(f"Predicted image not found at: {predicted_image_path}")
            print(f"Contents of {os.path.join(runs_dir, latest_run)}:")
            if os.path.exists(os.path.join(runs_dir, latest_run)):
                 print(os.listdir(os.path.join(runs_dir, latest_run)))
            else:
                 print("Latest run directory does not exist.")

    else:
        print("No prediction run directories found starting with 'predict'.")

import os
from IPython.display import Image, display
from ultralytics import YOLO

# Load the best model
model = YOLO("/content/drive/MyDrive/aod4_best.pt")

# Path to an image with a bird from the test set (using a different image)
image_to_predict = "/content/aod4/test/images/pexels-david-yu-3124958_jpg.rf.70b07333506a22b063fcf285b436f28b.jpg" # Another example image with birds

# Run prediction
results = model.predict(source=image_to_predict, save=True, conf=0.25)

# Check if any detections are found and if the detected classes include 'bird'
if results and len(results[0].boxes) > 0:
    detected_classes = [model.names[int(box.cls)] for box in results[0].boxes]
    if 'bird' in detected_classes:
        print(f"Detected bird in: {image_to_predict}")
        # Display the image with predictions
        # Find the latest prediction run directory, excluding 'val'
        runs_dir = '/content/runs/detect/'
        all_runs = [d for d in os.listdir(runs_dir) if os.path.isdir(os.path.join(runs_dir, d))]
        prediction_runs = [d for d in all_runs if not d.startswith('val')]
        latest_run = sorted(prediction_runs)[-1] if prediction_runs else None

        # Construct the predicted image path
        if latest_run:
            image_filename = os.path.basename(image_to_predict)
            predicted_image_path = os.path.join(runs_dir, latest_run, image_filename)
            if os.path.exists(predicted_image_path):
                display(Image(filename=predicted_image_path))
            else:
                print(f"Predicted image not found at: {predicted_image_path}")
        else:
            print("No prediction run directories found.")

import os
from IPython.display import Image, display
from ultralytics import YOLO

# Load the best model
model = YOLO("/content/drive/MyDrive/aod4_best_continued.pt")

# Path to an image with a helicopter from the test set
image_to_predict = "/content/aod4/test/images/V_HELICOPTER_051275_151_png_jpg.rf.0647c9d1cee197dced99c3cbde285ad7.jpg" # Example image with a helicopter

# Run prediction
results = model.predict(source=image_to_predict, save=True, conf=0.25)

# Check if any detections are found and if the detected classes include 'helicopter'
if results and len(results[0].boxes) > 0:
    detected_classes = [model.names[int(box.cls)] for box in results[0].boxes]
    if 'helicopter' in detected_classes:
        print(f"Detected helicopter in: {image_to_predict}")
        # Display the image with predictions
        # Find the latest prediction run directory, excluding 'val'
        runs_dir = '/content/runs/detect/'
        all_runs = [d for d in os.listdir(runs_dir) if os.path.isdir(os.path.join(runs_dir, d))]
        # Filter out directories that don't start with 'predict' and sort them numerically
        prediction_runs = []
        for d in all_runs:
            if d.startswith('predict'):
                try:
                    run_number = int(d.replace('predict', ''))
                    prediction_runs.append((run_number, d))
                except ValueError:
                    # Ignore directories that don't have a valid number after 'predict'
                    pass

        latest_run = sorted(prediction_runs)[-1][1] if prediction_runs else None

        # Debugging print statements
        print(f"All run directories: {all_runs}")
        print(f"Prediction run directories (filtered and sorted): {prediction_runs}")
        print(f"Latest prediction run directory identified: {latest_run}")


        # Construct the predicted image path
        if latest_run:
            image_filename = os.path.basename(image_to_predict)
            predicted_image_path = os.path.join(runs_dir, latest_run, image_filename)
            if os.path.exists(predicted_image_path):
                display(Image(filename=predicted_image_path))
            else:
                print(f"Predicted image not found at: {predicted_image_path}")
        else:
            print("No prediction run directories found.")

import os
import requests
from IPython.display import Image, display
from ultralytics import YOLO

# Load the best model from your Google Drive
model = YOLO("/content/drive/MyDrive/aod4_best_continued.pt")

# --- Specify the URL of your new image file here ---
image_url_bird_drone = "https://gradiant.org/wp-content/uploads/2020/09/Cabecera_AdobeStock_300246618.jpg" # Replace with the actual URL of your image

# Define a path to save the downloaded image
download_path = "/content/downloaded_image.jpg" # You can change the filename if needed

# Download the image from the URL
try:
    response = requests.get(image_url_bird_drone, stream=True)
    response.raise_for_status() # Raise an HTTPError for bad responses (4xx or 5xx)
    with open(download_path, 'wb') as f:
        for chunk in response.iter_content(chunk_size=8192):
            f.write(chunk)
    print(f"Image downloaded successfully to: {download_path}")

    # Run prediction on the downloaded image
    # save=True will save the predicted image with bounding boxes
    results_bird_drone = model.predict(source=download_path, save=True, conf=0.25)

    # Optional: Display the predicted image
    if results_bird_drone and len(results_bird_drone[0].boxes) > 0:
        print(f"Prediction results saved for: {download_path}")
        # Find the latest prediction run directory
        runs_dir = '/content/runs/detect/'
        all_runs = [d for d in os.listdir(runs_dir) if os.path.isdir(os.path.join(runs_dir, d))]
        # Filter out directories that don't start with 'predict' and sort them numerically
        prediction_runs = []
        for d in all_runs:
            if d.startswith('predict'):
                try:
                    run_number = int(d.replace('predict', ''))
                    prediction_runs.append((run_number, d))
                except ValueError:
                    # Ignore directories that don't have a valid number after 'predict'
                    pass

        latest_run = sorted(prediction_runs)[-1][1] if prediction_runs else None

        if latest_run:
            image_filename_bird_drone = os.path.basename(download_path)
            predicted_image_path_bird_drone = os.path.join(runs_dir, latest_run, image_filename_bird_drone)
            if os.path.exists(predicted_image_path_bird_drone):
                print("Displaying the predicted image with detections:")
                display(Image(filename=predicted_image_path_bird_drone))
            else:
                print(f"Predicted image not found at: {predicted_image_path_bird_drone}")
        else:
            print("No prediction run directories found.")
    else:
        print(f"No objects detected in {download_path}")

except requests.exceptions.RequestException as e:
    print(f"Error downloading image: {e}")
except Exception as e:
    print(f"An error occurred during prediction or display: {e}")



from ultralytics import YOLO

# Load the best model
model = YOLO("/content/drive/MyDrive/aod4_best_continued.pt")

# Evaluate the model on the validation set
metrics = model.val()

# Print the evaluation metrics
print("--- Model Evaluation Metrics ---")
print(f"mAP@0.5: {metrics.box.map50}")
print(f"mAP@0.5:0.95: {metrics.box.map}")
print(f"Precision: {metrics.box.p}")
print(f"Recall: {metrics.box.r}")
print("--------------------------------")

# You can access metrics for each class as well:
# print("\nMetrics per class:")
# for i, class_name in enumerate(model.names):
#     print(f"Class '{class_name}':")
#     print(f"  Precision: {metrics.box.p[i]}")
#     print(f"  Recall: {metrics.box.r[i]}")
#     print(f"  mAP@0.5: {metrics.box.map50[i]}")
#     print(f"  mAP@0.5:0.95: {metrics.box.map[i]}")

import os
from IPython.display import Image, display
from ultralytics import YOLO

# Load the best model (if not already loaded)
try:
    model
except NameError:
    model = YOLO("/content/drive/MyDrive/aod4_best_continued.pt")


# Find the latest validation run directory
runs_dir = '/content/runs/detect/'
# Get all entries in runs_dir that are directories and start with 'val'
val_runs = sorted([d for d in os.listdir(runs_dir) if os.path.isdir(os.path.join(runs_dir, d)) and d.startswith('val')],
                  key=lambda x: int(x.replace('val', '')) if x.replace('val', '').isdigit() else 0)

latest_val_run = val_runs[-1] if val_runs else None

if latest_val_run:
    latest_val_run_path = os.path.join(runs_dir, latest_val_run)
    print(f"Latest validation run directory: {latest_val_run_path}")

    # List some of the key visualization files saved by Ultralytics
    confusion_matrix_path = os.path.join(latest_val_run_path, 'confusion_matrix.png')
    pr_curve_path = os.path.join(latest_val_run_path, 'PR_curve.png')
    results_plot_path = os.path.join(latest_val_run_path, 'results.png')
    # You can also get metrics programmatically if you ran model.val() in a previous cell
    # For simplicity and to show visualizations, we focus on the saved plots here.


    print("\n--- Model Evaluation Visualizations ---")

    print("\nDisplaying Confusion Matrix:")
    if os.path.exists(confusion_matrix_path):
        display(Image(filename=confusion_matrix_path))
    else:
        print(f"Confusion matrix not found at: {confusion_matrix_path}")

    print("\nDisplaying Precision-Recall Curve:")
    if os.path.exists(pr_curve_path):
        display(Image(filename=pr_curve_path))
    else:
        print(f"Precision-Recall curve not found at: {pr_curve_path}")

    print("\nDisplaying Results Plot (Losses and Metrics over Epochs):")
    if os.path.exists(results_plot_path):
        display(Image(filename=results_plot_path))
    else:
        print(f"Results plot not found at: {results_plot_path}")

    # Display key metrics in percentage (assuming model.val() was run previously)
    try:
        if 'metrics' in locals() and metrics is not None:
             print("\n--- Model Accuracy Metrics ---")
             print(f"mAP@0.5 (mean Average Precision at 50% IoU): {metrics.box.map50 * 100:.2f}%")
             print(f"mAP@0.5:0.95 (mean Average Precision across various IoU thresholds): {metrics.box.map * 100:.2f}%")
             # You can add precision and recall here if needed, but mAP is a good overall indicator
             # print(f"Average Precision: {metrics.box.p.mean() * 100:.2f}%")
             # print(f"Average Recall: {metrics.box.r.mean() * 100:.2f}%")
             print("------------------------------")

        else:
            print("\nMetrics object not found. Please run model.val() in a previous cell to see accuracy metrics.")
    except Exception as e:
        print(f"\nAn error occurred while trying to display metrics: {e}")


else:
    print("No validation run directories found starting with 'val'.")